#!/home/duong/anaconda3/bin/python3
# SPDX-FileCopyrightText: 2025 duogg 　　　　　
# SPDX-License-Identifier: GPL-3.0-only

import sys

ans = 0  # もともと0.0だったのを0に変更
for line in sys.stdin:
    try:
        ans += int(line)   # intは文字列を整数に（失敗すると例外発生）
    except:
        ans += float(line)

print(ans)

